name: CI on Push
run-name: triggered a push workflow
on:
 push:
   branches:
     - main # Change to your target branch
jobs:
 build:
   runs-on: ubuntu-latest
   env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: '20'
     - run: npm install
     - run: npm test
